"""Declarative base shared by every ORM model.

Models import Base from here rather than defining their own, so that a single
`Base.metadata` sees every table when migrations are autogenerated.
"""

from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    """Base class for all ORM models."""
