"""create candidate profiles

Revision ID: 5439ba5c442b
Revises: 621a8f77b93d
Create Date: 2026-07-19 22:41:21.949501

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5439ba5c442b"
down_revision: str | None = "621a8f77b93d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("headline", sa.String(length=200), server_default="", nullable=False),
        sa.Column("location", sa.String(length=120), server_default="", nullable=False),
        sa.Column("phone", sa.String(length=40), server_default="", nullable=False),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "preferred_role", sa.String(length=200), server_default="", nullable=False
        ),
        sa.Column(
            "preferred_location", sa.String(length=120), server_default="", nullable=False
        ),
        sa.Column(
            "preferred_employment_type",
            sa.String(length=40),
            server_default="",
            nullable=False,
        ),
        sa.Column(
            "key_skills", sa.String(length=1000), server_default="", nullable=False
        ),
        sa.Column("employment", sa.Text(), server_default="", nullable=False),
        sa.Column("education", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candidate_profiles")
    # ### end Alembic commands ###
